[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
via_ir = true
ffi = false
rpc_endpoints = { 
  base_sepolia = "https://sepolia.base.org",
  base = "https://mainnet.base.org"
}
fs_permissions = [{ access = "read-write", path = "./"}]

[fmt]
multiline_func_header = "params_first"
