[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
via_ir = true
ffi = false

[rpc_endpoints]
local = "${RPC_URL_LOCAL}"
staging = "${RPC_URL_STAGING}"
production = "${RPC_URL_PRODUCTION}"

[etherscan]
base_sepolia = { key = "${BASESCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }
base = { key = "${BASESCAN_API_KEY}", url = "https://api.basescan.org/api" }
